CREATE TABLE User (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(50) COLLATE utf8_bin UNIQUE NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Password (
  UserID INT PRIMARY KEY,
  HashedPassword VARCHAR(255) NOT NULL,
  Salt VARCHAR(255) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Score (
  ID INT PRIMARY KEY
  Username VARCHAR(50) 
  Score INT 
);



